src/Entity/ImagesActivity.php
<?php

namespace App\Entity;

use App\Repository\ImagesActivityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesActivityRepository::class)]
class ImagesActivity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $image_url = null;

    //Relación con PersonalActivities: una foto pertenece a una actividad
    #[ORM\ManyToOne(targetEntity: PersonalActivities::class, inversedBy: 'imagesActivity')]
    private ?PersonalActivities $personalActivity = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getPersonalActivity(): ?PersonalActivities
    {
        return $this->personalActivity;
    }
    public function setPersonalActivity(?PersonalActivities $personalActivity): static
    {
        $this->personalActivity = $personalActivity;
        return $this;
    }

}

src/Form/UserProfileType.php
<?php

namespace App\Form;

use App\Entity\Provinces;
use App\Entity\Localities;
use App\Entity\User;
use App\Repository\ProvincesRepository;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Validator\Constraints as Assert;

class UserProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $options['data']; 

        $province = $user->getProvince();

        $builder
            ->add('userName', TextType::class, [ 'label' => 'Nombre de usuario', 'required' => false])
            ->add('name', TextType::class, ['label' => 'Nombre', 'required' => false])
            ->add('firstLastName', TextType::class, ['label' => 'Primer Apellido', 'required' => false])
            ->add('secondLastName', TextType::class, ['label' => 'Segundo Apellido', 'required' => false])
            ->add('phone', TextType::class, ['label' => 'Teléfono', 'required' => false])
            ->add('email', EmailType::class, ['label' => 'Correo Electrónico', 'required' => false])
            ->add('biography', TextareaType::class, ['label' => 'Biografía', 'required' => false])
            /*->add('photo', FileType::class, [
               'label' => 'Foto',
               'required' => false,
               'mapped' => false,
            ])*/
            ->add('province', EntityType::class, [
                'class'=> Provinces::class,
                'label' => 'Provincia',
                'required' => false,
                'query_builder' => function (ProvincesRepository $er) {
                    return $er->createQueryBuilder('p')
                        ->orderBy('p.name', 'ASC');
                    },
            ])
            ->add('locality', EntityType::class, [
                'class'=> Localities::class,
                'choices' => $province ? $province->getLocalities() : [], //si el usua tien eun aprovinciam se cargue directamente la localidad  
                'required' => false,
                'label' => 'Localidad'
            ])
            ->add('addres', TextType::class, ['label' => 'Dirección', 'required' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserProfileController.php
<?php

namespace App\Controller;

use App\Entity\CategoryActivity;
use App\Entity\User;
use App\Entity\PersonalActivities;

use App\Form\UserProfileType;
use App\Form\ChangePasswordType;
use App\Repository\CategoryActivityRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\HttpFoundation\JsonResponse;



final class UserProfileController extends AbstractController
{

    private $em;

    public function  __construct(EntityManagerInterface $em){
        $this->em = $em;
    }
    

    #[Route('/user/view_profile', name: 'app_user_view__profile')]
    public function profile(EntityManagerInterface $em, CategoryActivityRepository $categoryReposiotry): Response
    {
        $user = $this->getUser();

        //verificar que el usuario esé autenticado
        $this->denyAccessUnlessGranted('ROLE_USER');

        if(!$user instanceof \App\Entity\User) throw new \LogicException('El usuario no es válido');

        if (!$user->isProfileCompleted()) {
            $link = $this->generateUrl('edit_profile');
            $this->addFlash('warning', "Tu perfil está incompleto. <a href='$link'>Haz click aquí para completarlo</a> ");
        }
        
        $allActivities = $em->getRepository(PersonalActivities::class)->findBy(['user' => $user]);

        //Filtras si la activdad está o no está completada. fn es una función de filtrado, que toma el $a que represneta cada actividad del array
        $completedActivities = array_filter($allActivities, fn($a) => $a->isCompleted());
        $pendingActivities = array_filter($allActivities, fn($a) => !$a->isCompleted());

        $categories = $categoryReposiotry->findAll(); //obtener todas las categoróias para mostrarlas en el peril  

        //Haces un array que vincule cada categoría con un icono para mostrarla en la vista y que cada categoría tenga un icono diferente!
        $categoryIcons = [
            'aventura' => 'fa-tree',
            'bicicross' => 'fa-bicycle',
            'carreras' => 'fa-running',
            'ciclismo' => 'fa-bicycle',
            'deportes_acuaticos' => 'fa-water',
            'deportes_aereos' => 'fa-plane',
            'deportes_urbanos' => 'fa-city',
            'equitacion' => 'fa-horse',
            'escalada' => 'fa-hiking',
            'escapadas_activas' => 'fa-campground',
            'esqui_y_nieve' => 'fa-snowflake',
            'montanismo' => 'fa-mountain',
            'natacion' => 'fa-swimmer',
            'nauticos_y_navegacion' => 'fa-ship',
            'patinaje' => 'fa-skating',
            'puenting' => 'fa-road',
            'senderismo' => 'fa-walking',
            'skate' => 'fa-skating',
            'tiro_y_precision' => 'fa-bullseye',
        ];        

        //dump($categories); die;
        
        return $this->render('user_profile/view_profile.html.twig', [
            'user' => $user,
            'completedActivities' => $completedActivities,
            'pendingActivities' => $pendingActivities,
            'categories' => $categories,
            'categoryIcons' => $categoryIcons,
        ]);
    }

    #[Route('/user/edit/profile', name: 'edit_profile')]
    public function edit_profile(Request $request, EntityManagerInterface $em): Response
    {
        //primero obtener al usuario actual
        $user = $this->getUser();

        if (!$user instanceof User) throw $this->createNotFoundException('El usuario no está autenticado correctamente');

        // crear y manejar el form con los datos del user
        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

         /*manejar foto si sube una nueva sin clerk
        $file = $form->get('photo')->getData();
        if ($file) {
            $fileName = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move($this->getParameter('kernel.project_dir') . '/public/uploads/profile_photos', $fileName);
            $user->setPhoto($fileName);
        }*/
        
        $locality = $user->getLocality(); 
            if (!$locality) { 
                $user->setLocality(null);
            }

        //persistir cambios en la base de datos
        $em->flush();

        $this->addFlash('success', 'Tus datos se han actualizado correctamente');
        return $this->redirectToRoute('edit_profile');
    }

    // Renderiza la vista del formulario
    return $this->render('user_profile/edit_profile.html.twig', [
        'form' => $form->createView(),
    ]);
    }

    /*Método para cambiar la contraseña sin clerk:
    #[Route('/user/edit/password', name: 'edit_password')]
    public function editPassword(Request $request, EntityManagerInterface $em, userPasswordHasherInterface $userPassword){

        $user = $this->getUser();

        if(!$user instanceof User){
            throw $this->createNotFoundException('El usuario no está autenticado correctamente');
        }

        //Crear el formulario que cambia la contraseña
        $formPassword = $this->createForm(ChangePasswordType::class, $user);
        $formPassword->handleRequest($request);

        if($formPassword->isSubmitted() && $formPassword->isValid()){
            //Valida la contraseña actual:
            $currentPassword = $formPassword->get('currentPassword')->getData();
            $newPassword = $formPassword->get('newPassword')->getData();
            $confirmPassword = $formPassword->get('confirmPassword')->getData();

            if(!$userPassword->isPasswordValid($user, $currentPassword)){
                $this->addFlash('error', 'La contraseña actual no es válida');
            }elseif($newPassword !== $confirmPassword){
                $this->addFlash('error', 'Las contraseñas no coinciden');
            }else{
                $newPasswordHash = $userPassword->hashPassword($user, $newPassword);
                $user->setPassword($newPasswordHash); //aquí actualizas la contraseña
                $this->em->flush();
                $this->addFlash('success', 'Tu contraseña se ha actualizado correctamente');

                return $this->redirectToRoute('app_user_view__profile');
            }
        }

        return $this->render('user_profile/edit_password.html.twig', ['formPassword'  => $formPassword->createView()]);

    } cierre método cambio contraseña */

    //-----------Método para acompañante
    #[Route('/user/search', name: 'user_search', methods: ['GET'])]
    public function searchUser(Request $request, UserRepository $userRepository): JsonResponse
    {
        $query = $request->query->get('query'); // Lo que el usuario ha escrito
        $users = $userRepository->findBySearchQuery($query); // Método que hay que agregar en el repositorio de usuarios

        $userResults = [];
        foreach ($users as $user) {
            $userResults[] = [
                'id' => $user->getId(),
                'userName' => $user->getUserName(),
                'email' => $user->getEmail(),
            ];
        }

        return new JsonResponse($userResults);
    }

    //---------------Mostrar iconos con las categorías en el perfil del usuario---------------------------
    #[Route('/personalActivity/categoria/{id}', name: 'show_subcategories')]
    public function showSubcagtegories(CategoryActivity $category): Response
    {
        return $this->render('PersonalActivity/subcategories.html.twig', [
            'category' => $category,
            'subcategories' => $category->getSubcategories()
        ]);
    }



} //fin controller

templates/user_profile/edit_password.html.twig
{% extends 'base_user.html.twig' %}

{% block title %}Actualiza tu contraseña{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2 class="text-center">Actualiza la contraseña</h2>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="tab-pane fade show active" id="passwordTab">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Configura tu contraseña</h5>
            </div>

            <div class="card-body pt-0">
                {{ form_start(formPassword, {'attr': {'data-turbo': 'false'}, 'method': 'POST', 'action': path('edit_password')})}}
                
                <div class="mb-3">
                    <label class="form-label" for="currentPassword">Contraseña Actual</label>
					{{ form_widget(formPassword.currentPassword, {'attr': {'class': 'form-control', 'placeholder': 'Introduce tu contraseña actual'}}) }}
				</div>

                <div class="mb-3">
                    <label class="form-label" for="newPassword">Nueva contraseña</label>
                    {{ form_widget(formPassword.newPassword, {'attr': {'class': 'form-control', 'placeholder': 'Introduce tu nueva contraseña'}})}}
                </div>

                <div class="mb-3">
                    <label class="form-label" for="confirmPassword">Confirma la nueva contraseña</label>
                    {{ form_widget(formPassword.confirmPassword, {'attr': {'class': 'form-control', 'placeholder': 'Confirma tu nueva contraseña'}})}}
                </div>

                <button type="submit" class="btn btn-primary">Actualizar contraseña</button>

                {{ form_end(formPassword) }}

            </div>

        </div>
    </div>



{% endblock %}

templates/user_profile/view_profile.html.twig
{% extends 'base_user.html.twig' %}

{% block title %}Perfil de usuario{% endblock %}

{% block content %}

    <!--Mensaje flash de éxito para cuando cambias la contraseña: al cambiar la contraseña, te lleva a la página del usuario y el mensaje saldrá aquí. Sin clerk-->
    <!--Mensjae flash de éxito cuando modificas, creas y eliminas una actividad!-->
    {% for message in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    

    <!---Mensaje flash para cuando el usuario viene del registro y aún no tiene el perfil completo-->
    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message|raw }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}


   <!-- Perfil de usuario y actividades -->
            <div class="row">
                
                <!-- Columna de perfil -->
                <div class="col-md-4">
                    <div class="card">
                        
                        {#
                        {% if app.user.photo %}
                            <img src="{{ asset('uploads/profile_photos/' ~ app.user.photo) }}" alt="Foto de perfil" class="card-img-top profile-photo">
                        {% else %}
                            <img src="{{ asset('images/default.png') }}" alt="Foto de perfil" class="card-img-top profile-photo">
                        {% endif %}
                        
                        #}


                        <!--<img id="user-avatar" src="{{ asset('images/default.png') }}" alt="Foto de perfil" class="card-img-top profile-photo">-->
                        <img id="user-avatar" class="card-img-top profile-photo d-none" alt="Foto de perfil">

                        <div class="card-body">
                            <h5 class="card-title"> {{app.user.name}} </h5>
                            <p class="card-text"> {{app.user.biography}} </p>
                        </div>
                        
                    </div>
                </div>

                  <!-- Columna de actividades -->
                <div class="col-md-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h5 class="card-title">Actividades Completadas</h5>
                            </div>
                            <div class="d-flex flex-wrap gap-3 justify-content-start">
                            
                                {% for activity in completedActivities %}
                                
                                    <div class="text-center activity-item">
                                      {% set iconKey = activity.categoryActivity.name|lower|replace({'á':'a','é':'e','í':'i','ó':'o','ú':'u',' ':'_', 'ñ':'n'}) %}
                                        
                                        {% if activity.imagesActivity|length > 0 %}
                                        <div class="img-container">
                                            <img src="{{ asset('uploads/activity_images/' ~ activity.imagesActivity[0].imageUrl) }}" class="rounded-circle" alt="actividad" style="width: 150px; height: 150px; object-fit: cover;">
                                            
                                            <div class="icon-overplay">
                                               <a href="{{ path('app_view_activities', { id: activity.id }) }}" class="icon-btn"> <i class="fas fa-eye"></i> </a>
                                               
                                               <a href="{{ path('edit_activity', {'id': activity.id})}}" class="icon-btn"> <i class="fas fa-pen"></i></a>
                                            </div>

                                        </div>
                                        {% else %}
                                        <div class="img-container d-flex align-items-center justify-content-center rounded-circle border bg-light" style="width: 150px; height: 150px;">
                                            <i class="fas {{ categoryIcons[iconKey]|default('fa-question') }} fa-3x text-muted"></i>

                                            <div class="icon-overplay">
                                                <a href="{{ path('app_view_activities', { id: activity.id }) }}" class="icon-btn"> <i class="fas fa-eye"></i> </a>
                                                <a href="{{ path('edit_activity', {'id': activity.id})}}" class="icon-btn"> <i class="fas fa-pen"></i></a>
                                            </div>

                                        </div>
                                        {% endif %}
                                        </a>
                                        <p class="small">{{ activity.getNameActivity() }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="card">
                       <div class="card-body">
                           <h5 class="card-title">Explora las actividades</h5>
                           <div class="flex-activities">
                               {% for category in categories %}
                                  {#Normalizar el nombre de la cat para poder usarlo como clave en el array de iconos. Si no, no coge el icono y sale el defaul siempre#}
                                  {% set iconKey = category.name|lower|replace({'á':'a', 'é':'e', 'í':'i', 'ó':'o', 'ú':'u', ' ':'_', 'ñ':'n'}) %}
                                  
                                    <!--Dropdown para que salgan las categorías monas-->
                                    <div class="dropdown">
                                        <div class="category-link" data-id="{{ category.id}}" data-bs-toggle="dropdown" aria-expanded="false" style="cursos:pointer;">
                                            <div class="rounded-circle border border-primary text-primary d-flex align-items-center justify-content-center category-icon" style="width: 100px; height: 100px;">
                                                <i class="fas {{ categoryIcons[iconKey]|default('fa-question') }} fa-2x"></i>
                                            </div>
                                            <p class="small mt-2" style="text-align:center;"> {{category.name}} </p>
                                        </div>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ category.id }}">
                                            {% for subcategory in category.subcategories %}
                                                <li>
                                                    <a class="dropdown-item subcategory-card" data-id="{{ subcategory.id }}" data-category-id="{{ category.id}}" href="#"> {{ subcategory.name }} </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                               {% endfor %}
                           </div>
                       </div>
                    </div>
                </div>
           
            </div><!--Fin div class row del perfil de usuario y actividades-->
        </div><!--Fin div class container-->

<script async crossorigin="anonymous"
    src="https://deciding-gar-25.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js"
    data-clerk-publishable-key="pk_test_ZGVjaWRpbmctZ2FyLTI1LmNsZXJrLmFjY291bnRzLmRldiQ">
</script>

<script>
document.addEventListener('DOMContentLoaded', async () => { 
    await Clerk.load();

    const user = await Clerk.user;
    const avatar = document.getElementById('user-avatar');

    if(user && avatar){
        avatar.src = user.imageUrl || '/images/default.png';
        avatar.classList.remove('d-none'); //mostrar img solo cuando esté lista
    }

    /*---------------------Redirigiri para crear actividad*/
    const createActivityUrl = '{{ path("app_activity_new")}}';

    document.querySelectorAll('.subcategory-card').forEach(card => {
        card.addEventListener('click', (e) => {
            e.preventDefault();
            const subcatId = card.dataset.id;
            const catId = card.dataset.categoryId;
            window.location.href = `${createActivityUrl}?categoryActivity=${catId}&subcategoryActivity=${subcatId}`;
        });
    });

}); //cierre DOM
</script>
{% endblock %}